Lebedeva/converter
droidroot1995/DAFE_Python_course_homeworks_2019_2020 pull request #5
Opened 2020-05-05 18:18 UTC by lebedevarina

2020-05-08 15:22 UTC, droidroot1995 commented
Поместить всё, кроме README.md, в папку со именем Name_Surname. Добавить всем скриптам расширение .py

2020-05-09 14:25 UTC, droidroot1995 commented on Arina_Lebedeva/matplotlib/poisson.py
> +y = ((np.exp(-mu) * mu * x)/np.math.factorial(x))
Разобраться почему крашится в этом месте.

2020-05-09 14:42 UTC, droidroot1995 requested changes

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/matplotlib/poisson.py
> +y = ((np.exp(-mu) * mu * x)/np.math.factorial(x))
Разобраться почему крашится в этом месте.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/diff.py
> +plt.show()
Функцию необходимо было взять у преподавателя во время занятия. Необходимо построить график функции.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/diff.py
> +print (d_fun(x))
Необходимо хотя бы вывести координаты точки, в которой вычисляется производная.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/rectangle_integral.py
> +x = fun(x)
Крашится в этом месте. Поправить.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/simpson_integration.py
> +x = fun(x)
Крашится в этом месте. Поправить.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/trapezoid_integration.py
> +x = fun(x)
Крашится в этом месте. Поправить.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/3 methods_plot.py
> +pylab.plot(xlist, ylist3)
Зачем, если импортирован matplotlib? Почему отличаются графики интегралов? Необходимо было построить график функции, а не интегралов.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/converter.py
> +print (currency.current_converted_price * money)
Это не конвертер, а парсер. Внимательно читаем задание.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/mechanical_sys/falling_with_angle.py
> +t = linspace(0, 1, 1001)
Крашится в этом месте.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/mechanical_sys/falling_with_angle.py
> +plt.show()
Необходимо было нарисовать анимацию, а не статику. Что изображено на графиках - непонятно. Какой из случаев реализован упругий или неупругий удар - непонятно.

2020-05-09 14:42 UTC, droidroot1995 commented on Arina_Lebedeva/mechanical_sys/falling.py
> +plt.show()
Необходимо было нарисовать анимацию, а не статику. Что изображено на графиках - непонятно. Какой из случаев реализован упругий или неупругий удар - непонятно.

2020-05-10 12:19 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/diff.py
> +plt.show()
Можно сейчас получить функцию? Пока что внесла все правки на своем примере

2020-05-10 12:19 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/diff.py
> +print (d_fun(x))
Исправила

2020-05-10 12:23 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/rectangle_integral.py
> +x = fun(x)
У меня не выдает ошибок, поэтому не знаю, что нужно поправлять

2020-05-10 12:29 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/simpson_integration.py
> +x = fun(x)
Здесь то же самое, ошибки не возникает

2020-05-10 12:35 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/3 methods_plot.py
> +pylab.plot(xlist, ylist3)
Исправила

2020-05-10 12:59 UTC, lebedevarina commented on Arina_Lebedeva/mechanical_sys/falling_with_angle.py
> +t = linspace(0, 1, 1001)
исправила

2020-05-10 13:34 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/rectangle_integral.py
> +x = fun(x)
x = fun(x)

2020-05-10 13:34 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/simpson_integration.py
> +x = fun(x)
x = fun(x)

2020-05-10 13:35 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/trapezoid_integration.py
> +x = fun(x)
x = fun(x)

2020-05-10 13:36 UTC, droidroot1995 commented on Arina_Lebedeva/numerical_methods/diff.py
> +plt.show()
(e^x)*sin(x) [0, 1]

2020-05-10 13:51 UTC, lebedevarina commented on Arina_Lebedeva/numerical_methods/diff.py
> +plt.show()
сделано

2020-05-10 18:21 UTC, droidroot1995 commented on Arina_Lebedeva/mechanical_sys/falling_with_angle.py
> +t = linspace(0.0000001, 1, 1001)
Ничего не изменилось кроме правой границы. Всё-равно крашится. Нет анимации.

2020-05-10 18:21 UTC, droidroot1995 commented on Arina_Lebedeva/mechanical_sys/falling.py
>  y = (y0 + v0*t + 0.5*g*t**2) * (-1)
Нет анимации.

2020-05-10 18:21 UTC, droidroot1995 approved these changes

2020-05-10 18:22 UTC, droidroot1995 approved these changes

2020-05-10 18:23 UTC, droidroot1995 approved these changes

2020-05-10 18:24 UTC, merged