Snezskaya
droidroot1995/DAFE_Python_course_homeworks_2019_2020 pull request #6
Opened 2020-05-06 12:25 UTC by alisasnezskaya

2020-05-08 14:53 UTC, droidroot1995 commented
sin и rectangle - один и тот же файл.

2020-05-08 15:09 UTC, droidroot1995 requested changes

2020-05-08 15:09 UTC, droidroot1995 commented on matplotlib/sin
> +plt.show()
То же самое, что и в rectangle

2020-05-08 15:12 UTC, droidroot1995 requested changes

2020-05-08 15:12 UTC, droidroot1995 commented on matplotlib/poisson
> +y = ((np.exp(-1.5))*1.5*x)/(np.math.factorial(x))
Проверить, почему программа падает в этом месте

2020-05-10 13:35 UTC, alisasnezskaya commented on matplotlib/sin
> +plt.show()
исправила

2020-05-10 13:36 UTC, alisasnezskaya commented on matplotlib/poisson
> +y = ((np.exp(-1.5))*1.5*x)/(np.math.factorial(x))
(функция, которую вы определила, ожидает один параметр, но вместо него получает массив)
исправила

2020-05-10 17:51 UTC, droidroot1995 approved these changes

2020-05-10 17:51 UTC, merged